# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prototype <- function(X) {
    .Call(`_mtrToolkit_prototype`, X)
}

variance <- function(X) {
    .Call(`_mtrToolkit_variance`, X)
}

homogeneity <- function(X) {
    .Call(`_mtrToolkit_homogeneity`, X)
}

euclideanDist <- function(x, y) {
    .Call(`_mtrToolkit_euclideanDist`, x, y)
}

calcEuclideanDist <- function(x, centroid) {
    .Call(`_mtrToolkit_calcEuclideanDist`, x, centroid)
}

col_vars <- function(X) {
    .Call(`_mtrToolkit_col_vars`, X)
}

best_split <- function(attr, Y, actual_var, actual_ss, ftest_signf = 0.05) {
    .Call(`_mtrToolkit_best_split`, attr, Y, actual_var, actual_ss, ftest_signf)
}

